### PR TITLE
Feature backend/auth

### PR DESCRIPTION
**Pull request by SymonMuchemi**

### CODE REVIEW

**Comment by SymonMuchemi** [comment]
I need help testing the authentication part.

**Comment by victorkamoto** [comment]
In the middleware the wrong env var is used, `ACCESS_TOKEN_SECRET` instead of `JWT_SECRET`.

After register, the password isn't hashed: 
```json
{
        "email": "foo@foo.mail",
        "name": "John Doe",
        "password": "some-secret-pwd",
        "role": "member",
        "xata_createdat": "2024-10-20T16:58:14.771Z",
        "xata_id": "1",
        "xata_updatedat": "2024-10-20T16:58:14.771Z",
        "xata_version": 0
    }
```

This also implies login is not working

**Comment by SymonMuchemi** [comment]
I created that user manually before writing the registration routes.

**Comment by victorkamoto** [comment]
Oh I was looking at the wrong record

My John Doe:
```json
    {
        "email": "jdoe@email.com",
        "name": "John Doe",
        "password": "$2a$10$nr/6CTa7VDgobSGjPsSxmObkQbkUI6nXMNwW.mKkAKJJdHvKoyUQy",
        "role": "member",
        "xata_createdat": "2024-10-21T10:50:51.044Z",
        "xata_id": "rec_csb342urlsprh6ribnfg",
        "xata_updatedat": "2024-10-21T10:50:51.044Z",
        "xata_version": 0
    }
```
Authentication looks good

**Review by victorkamoto — APPROVED** [review]

**Review by MwangangiBrian — APPROVED** [review]

**Pull request merged**
